echo "-----------------------------------------"
echo "| ClaferWiki v0.3.6                     |"
echo "| https://github.com/gsdlab/claferwiki/ |"
echo "| By Michal Antkiewicz, Chris Walker    |"
echo "| Generative Software Development Lab   |"
echo "| Using `clafer -V`                     |"
echo "-----------------------------------------"
echo ""
echo "Starting gitit..."
echo ""
gitit -f gitit.cnf