echo "-----------------------------------------"
echo "| ClaferWiki v0.3.2.19-01-2013          |"
echo "| By Chris Walker, Michał Antkiewicz    |"
echo "| https://github.com/gsdlab/claferwiki/ |"
echo "|---------------------------------------|"
echo "| Using Clafer v0.3.2.3-11-2012         |"
echo "-----------------------------------------"
echo ""
echo "Starting gitit..."
echo ""
gitit -f gitit.cnf