echo "-----------------------------------------"
echo "| ClaferWiki v0.3.4.20-9-2013           |"
echo "| https://github.com/gsdlab/claferwiki/ |"
echo "| By Chris Walker, Michal Antkiewicz    |"
echo "| Generative Software Development Lab   |"
echo "| Using `clafer -V`                     |"
echo "-----------------------------------------"
echo ""
echo "Starting gitit..."
echo ""
gitit -f gitit.cnf