# For GHC-9.4.6
extra-deps:
  - gitit-0.15.1.1
  - url-2.1.3
  - filestore-0.6.5
  - recaptcha-0.1.0.4
  - github: nikomi/json-builder
    commit: fef4700b53da502f8d70d2106c9f4b65e1a69b3f
  - github: gsdlab/StringMap
    commit: 0fe1e8e3919de3077b40a61f54cb681c3548307e

resolver: lts-21.8

flags:
  sendfile:
    portable: true
  gitit:
    plugins: true

packages:
- '../clafer'
- '.'
