# For GHC-8.0.1 (does not build yet)
# extra-deps:
#   - data-stringmap-1.0.1.1
#   - json-builder-0.3
#   - gitit-0.12.1.1
#   - sendfile-0.7.9
#   - filestore-0.6.2
#   - json-0.9.1
#   - recaptcha-0.1.0.3
#   - uri-0.1.6.4
# resolver: nightly-2016-06-21

# for GHC-7.10.3
extra-deps:
  - data-stringmap-1.0.1.1
  - gitit-0.12.1.1
  - filestore-0.6.2
  - recaptcha-0.1.0.3
  - uri-0.1.6.4
  - sendfile-0.7.9
resolver: lts-6.4

flags:
  sendfile:
    portable: true
  gitit:
    plugins: true
    network-uri: true
    https: true
    highlighting: true

packages:
- '../clafer'
- '.'
