# For GHC-8.0.2
extra-deps:
  - data-stringmap-1.0.1.1
  - gitit-0.12.2.1
  - sendfile-0.7.9
  - filestore-0.6.3.1
  - json-0.9.1
  - json-builder-0.3
  - recaptcha-0.1.0.3
  - uri-0.1.6.4
  - tagsoup-0.14.1
  - cond-0.4.1.1
resolver: lts-8.5

flags:
  sendfile:
    portable: true
  gitit:
    plugins: true
    network-uri: true
    https: true
    highlighting: true

packages:
- '../clafer'
- '.'
